apiVersion: v2
name: banjo-alpha-deps
description: "Umbrella chart for alpha-environment dependencies (tcpg, dragonfly, minio, mailpit)."
type: application
version: 0.3.0  # managed by release.sh
sources:
  - https://github.com/toggle-corp/banjo-alpha-deps
dependencies:
  - name: dragonfly
    version: v1.38.0
    repository: oci://ghcr.io/dragonflydb/dragonfly/helm
    condition: dragonfly.enabled
  - name: minio
    version: 17.0.21
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: minio.enabled
