apiVersion: v2
name: banjo-alpha-deps
description: "Umbrella chart for alpha-environment dependencies (tcpg, garage, dragonfly)."
type: application
version: 0.0.1  # managed by release.sh
sources:
  - https://gitea.local.togglecorp.com/tc-infra/tcpg
