apiVersion: v2
name: toggle-postgres
description: "Helm Chart to deploy Simple Postgres (for alpha instances)"
type: application
version: 0.0.1  # managed by release.sh
sources:
  - https://github.com/toggle-corp
