{{- if and .Values.tcpg.enabled .Values.tcpg.auth.dumpPath }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tcpg.fullname" . }}-restore
  labels:
    {{- include "tcpg.labels" . | nindent 4 }}
  {{- with .Values.tcpg.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  10-restore.sh: |
{{ .Files.Get "scripts/10-restore.sh" | indent 4 }}
  entrypoint-wrapper.sh: |
{{ .Files.Get "scripts/entrypoint-wrapper.sh" | indent 4 }}
{{- end }}
