{{- if .Values.tcpg.enabled }}
{{- if and .Values.tcpg.init.restore.enabled (ne .Values.tcpg.init.restore.auth.type "none") .Values.tcpg.init.restore.auth.value (not .Values.tcpg.init.restore.auth.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tcpg.restoreSecretName" . }}
  labels:
    {{- include "tcpg.labels" . | nindent 4 }}
  {{- with .Values.tcpg.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  RESTORE_AUTH_VALUE: {{ .Values.tcpg.init.restore.auth.value | quote }}
{{- end }}
{{- end }}
