{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "tcpg.fullname" . }}
  labels:
    {{- include "tcpg.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "tcpg.selectorLabels" . | nindent 6 }}
{{- end }}
