{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "tcpg.fullname" . }}-pg-data
  labels:
    {{- include "tcpg.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ required "persistence.size is required" .Values.persistence.size | quote }}
{{- end }}
