apiVersion: v1
kind: Service
metadata:
  name: {{ template "tcpg.fullname" . }}
  labels:
    {{- include "tcpg.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "tcpg.selectorLabels" . | nindent 4 }}
