apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "toggle-postgres.fullname" . }}-pg
  {{- with (include "toggle-postgres.appDefaultDeploymentAnnotations" $) -}}{{ . | nindent 2 }}{{- end }}
  labels:
    app: {{ include "toggle-postgres.fullname" . }}
    component: toggle-postgres
spec:
  replicas: 1  # This should only 1
  selector:
    matchLabels:
      app: {{ include "toggle-postgres.fullname" . }}
      component: toggle-postgres
  template:
    metadata:
      annotations:
        {{- include "toggle-postgres.appDefaultAnnotations" $ | nindent 8 }}
      labels:
        app: {{ include "toggle-postgres.fullname" . }}
        component: toggle-postgres
    spec:
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: {{ template "toggle-postgres.fullname" . }}-pg-data
      {{- end }}
      containers:
        - name: pg
          image: "{{ printf "%s:%s" .Values.image.repository .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.image.pullSecrets }}
          imagePullSecrets:
          {{- toYaml . | nindent 2 }}
          {{- end }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready -U postgres -h 127.0.0.1 -p 5432
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready -U postgres -h 127.0.0.1 -p 5432
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready -U postgres -h 127.0.0.1 -p 5432
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ template "toggle-postgres.secretname" . }}
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: pg-data
