{{- $secretName := printf "%s-credentials" (include "mychart.fullname" .) -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName -}}

kind: Secret
apiVersion: v1
metadata:
  name: {{ template "toggle-postgres.secretname" . }}
  labels:
    app: {{ include "toggle-postgres.fullname" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  username: postgres
  password: {{ if $existing }}{{ index $existing.data "password" }}{{ else }}{{ randAlphaNum 24 | b64enc }}{{ end }}
  # TODO: host, port, dbname
